# Generated by Django 4.2.6 on 2024-01-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Sofa'), (2, 'Tables'), (3, 'Chairs')], verbose_name='Category'),
        ),
    ]
